mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: 0
      field-strategy: 1
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 请求和响应压缩配置
feign:
  # 开启hystrix降级
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  compression:
    request:
      enabled: true
    response:
      enabled: true

# https://cloud.spring.io/spring-cloud-static/Greenwich.SR1/single/spring-cloud.html#spring-cloud-consul-hystrix
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 5000
  shareSecurityContext: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

# 监控
management:
  endpoints:
    web:
      exposure:
        include: '*'

# 加密配置
jasypt:
  encryptor:
    password: zppcloud

# 安全模块配置
security:
  code:
    image:
      length: 4
      width: 100
  oauth2:
    tokenStore: redis
    jwtSigningKey: zpp
    clients[0]:
      clientId: zpp
      clientSecret: zpp
      # clientId对应的token的有效期，单位：s
      accessTokenValidateSeconds: 3600
  # 社交登录配置
  social:
    weixin:
      app-id: ENC(IbmvPODFXzeMD41Ip96fyyGcCbWBTeDeaCSW8255mJA=)
      app-secret: ENC(H2WPqrBYGJDd9n+xxVP98zNCEwwnI0wYk/0Dx/hhSHldAg5WvcL7/Oe1FhXaeW/v)
    qq:
      app-id: 101386962
      app-secret: 2a0f820407df400b84a854d054be8b6a
      providerId: qq