spring:
  datasource:
      name: test
      url: jdbc:mysql://localhost:3306/zpp-springcloud?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8
      username: root
      password: 123456
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

management:
  metrics:
    web:
      server:
        auto-time-requests: false

sleuth:
  enabled: true

zipkin:
  storage:
    type: mysql

